document.writeln("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">");
document.writeln("    <style>");
document.writeln("        * {");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;");
document.writeln("            box-sizing: border-box;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        ");
document.writeln("        ");
document.writeln("        ");
document.writeln("        .ad-modal {");
document.writeln("            display: flex;");
document.writeln("            position: fixed;");
document.writeln("            top: 0;");
document.writeln("            left: 0;");
document.writeln("            width: 100%;");
document.writeln("            height: 100%;");
document.writeln("            background-color: rgba(0, 0, 0, 0.9);");
document.writeln("            z-index: 10000;");
document.writeln("            align-items: center;");
document.writeln("            justify-content: center;");
document.writeln("            padding: 15px;");
document.writeln("            animation: fadeIn 0.5s ease;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        @keyframes fadeIn {");
document.writeln("            from { opacity: 0; }");
document.writeln("            to { opacity: 1; }");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .modal-content {");
document.writeln("            background: linear-gradient(135deg, #ffffff, #f9f9f9);");
document.writeln("            border-radius: 20px;");
document.writeln("            width: 100%;");
document.writeln("            max-width: 420px;");
document.writeln("            box-shadow: 0 25px 60px rgba(0, 0, 0, 0.5);");
document.writeln("            overflow: hidden;");
document.writeln("            position: relative;");
document.writeln("            animation: modalAppear 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.275);");
document.writeln("            border: 3px solid #e74c3c;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        @keyframes modalAppear {");
document.writeln("            from { opacity: 0; transform: scale(0.85) translateY(40px); }");
document.writeln("            to { opacity: 1; transform: scale(1) translateY(0); }");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .modal-header {");
document.writeln("            background: linear-gradient(to right, #e74c3c, #c0392b);");
document.writeln("            color: white;");
document.writeln("            padding: 20px 15px;");
document.writeln("            text-align: center;");
document.writeln("            position: relative;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .modal-header h2 {");
document.writeln("            font-size: 1.6rem;");
document.writeln("            margin-bottom: 8px;");
document.writeln("            display: flex;");
document.writeln("            align-items: center;");
document.writeln("            justify-content: center;");
document.writeln("            gap: 8px;");
document.writeln("            padding: 0 10px;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .modal-header p {");
document.writeln("            font-size: 1.1rem;");
document.writeln("            display: flex;");
document.writeln("            align-items: center;");
document.writeln("            justify-content: center;");
document.writeln("            gap: 8px;");
document.writeln("            padding: 0 10px;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .modal-body {");
document.writeln("            padding: 20px 15px;");
document.writeln("            text-align: center;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .modal-body p {");
document.writeln("            font-size: 1rem;");
document.writeln("            line-height: 1.6;");
document.writeln("            color: #555;");
document.writeln("            margin-bottom: 12px;");
document.writeln("            text-align: left;");
document.writeln("            padding-left: 5px;");
document.writeln("            display: flex;");
document.writeln("            align-items: flex-start;");
document.writeln("            gap: 8px;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .ad-image {");
document.writeln("            width: 100%;");
document.writeln("            margin: 15px 0;");
document.writeln("            border-radius: 12px;");
document.writeln("            overflow: hidden;");
document.writeln("            box-shadow: 0 5px 15px rgba(0,0,0,0.1);");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .ad-image img {");
document.writeln("            width: 100%;");
document.writeln("            height: auto;");
document.writeln("            display: block;");
document.writeln("            object-fit: cover;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .links-container {");
document.writeln("            background: #f8f9fa;");
document.writeln("            border-radius: 12px;");
document.writeln("            padding: 15px;");
document.writeln("            margin: 15px 0;");
document.writeln("            text-align: left;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .link-item {");
document.writeln("            margin-bottom: 12px;");
document.writeln("            padding: 12px;");
document.writeln("            background: white;");
document.writeln("            border-radius: 8px;");
document.writeln("            display: flex;");
document.writeln("            align-items: center;");
document.writeln("            transition: all 0.3s ease;");
document.writeln("            border-left: 4px solid #3498db;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .link-item:hover {");
document.writeln("            transform: translateX(5px);");
document.writeln("            box-shadow: 0 4px 12px rgba(0,0,0,0.1);");
document.writeln("            border-left: 4px solid #e74c3c;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .link-icon {");
document.writeln("            font-size: 1.3rem;");
document.writeln("            color: #e74c3c;");
document.writeln("            margin-right: 12px;");
document.writeln("            min-width: 25px;");
document.writeln("            text-align: center;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .link-text {");
document.writeln("            flex: 1;");
document.writeln("            overflow: hidden;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .link-text a {");
document.writeln("            color: #3498db;");
document.writeln("            text-decoration: none;");
document.writeln("            font-weight: bold;");
document.writeln("            font-size: 0.95rem;");
document.writeln("            word-break: break-all;");
document.writeln("            display: block;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .link-text a:hover {");
document.writeln("            text-decoration: underline;");
document.writeln("            color: #e74c3c;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .tags {");
document.writeln("            display: flex;");
document.writeln("            flex-wrap: wrap;");
document.writeln("            gap: 8px;");
document.writeln("            justify-content: center;");
document.writeln("            margin-top: 15px;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .tag {");
document.writeln("            background: #e74c3c;");
document.writeln("            color: white;");
document.writeln("            padding: 4px 12px;");
document.writeln("            border-radius: 20px;");
document.writeln("            font-size: 0.85rem;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .close-button {");
document.writeln("            position: absolute;");
document.writeln("            top: 12px;");
document.writeln("            right: 15px;");
document.writeln("            font-size: 1.8rem;");
document.writeln("            color: white;");
document.writeln("            cursor: pointer;");
document.writeln("            transition: transform 0.3s ease;");
document.writeln("            background: rgba(0,0,0,0.2);");
document.writeln("            width: 36px;");
document.writeln("            height: 36px;");
document.writeln("            border-radius: 50%;");
document.writeln("            display: flex;");
document.writeln("            align-items: center;");
document.writeln("            justify-content: center;");
document.writeln("            line-height: 1;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .close-button:hover {");
document.writeln("            transform: rotate(90deg) scale(1.1);");
document.writeln("            background: rgba(0,0,0,0.4);");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .countdown-bar {");
document.writeln("            height: 6px;");
document.writeln("            background: #ecf0f1;");
document.writeln("            border-radius: 3px;");
document.writeln("            margin-top: 20px;");
document.writeln("            overflow: hidden;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .countdown-progress {");
document.writeln("            height: 100%;");
document.writeln("            width: 100%;");
document.writeln("            background: linear-gradient(to right, #2ecc71, #3498db);");
document.writeln("            border-radius: 3px;");
document.writeln("            animation: countdown 10s linear forwards;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        @keyframes countdown {");
document.writeln("            from { width: 100%; }");
document.writeln("            to { width: 0%; }");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .countdown-text {");
document.writeln("            font-size: 0.9rem;");
document.writeln("            color: #7f8c8d;");
document.writeln("            margin-top: 10px;");
document.writeln("            text-align: center;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .ad-badge {");
document.writeln("            position: absolute;");
document.writeln("            top: 50px;");
document.writeln("            right: -10px;");
document.writeln("            background: #e74c3c;");
document.writeln("            color: white;");
document.writeln("            font-weight: bold;");
document.writeln("            padding: 4px 12px;");
document.writeln("            border-radius: 20px;");
document.writeln("            font-size: 0.8rem;");
document.writeln("            transform: rotate(5deg);");
document.writeln("            box-shadow: 0 4px 12px rgba(0,0,0,0.2);");
document.writeln("            z-index: 10;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        .mobile-indicator {");
document.writeln("            display: none;");
document.writeln("            text-align: center;");
document.writeln("            background: rgba(255, 255, 255, 0.2);");
document.writeln("            padding: 10px;");
document.writeln("            border-radius: 10px;");
document.writeln("            margin-top: 15px;");
document.writeln("            color: white;");
document.writeln("        }");
document.writeln("        ");
document.writeln("        /* 移动端优化 */");
document.writeln("        @media (max-width: 768px) {");
document.writeln("            .modal-header h2 {");
document.writeln("                font-size: 1.4rem;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .modal-header p {");
document.writeln("                font-size: 1rem;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .modal-body p {");
document.writeln("                font-size: 0.95rem;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .link-item {");
document.writeln("                padding: 10px;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .link-text a {");
document.writeln("                font-size: 0.9rem;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .mobile-indicator {");
document.writeln("                display: block;");
document.writeln("            }");
document.writeln("        }");
document.writeln("        ");
document.writeln("        @media (max-width: 480px) {");
document.writeln("            .modal-content {");
document.writeln("                border-radius: 18px;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .modal-header {");
document.writeln("                padding: 18px 12px;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .modal-header h2 {");
document.writeln("                font-size: 1.3rem;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .modal-header p {");
document.writeln("                font-size: 0.95rem;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .modal-body {");
document.writeln("                padding: 15px 12px;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .modal-body p {");
document.writeln("                font-size: 0.9rem;");
document.writeln("                margin-bottom: 10px;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .links-container {");
document.writeln("                padding: 12px;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .link-icon {");
document.writeln("                font-size: 1.1rem;");
document.writeln("                margin-right: 10px;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            .close-button {");
document.writeln("                top: 10px;");
document.writeln("                right: 12px;");
document.writeln("                font-size: 1.6rem;");
document.writeln("                width: 32px;");
document.writeln("                height: 32px;");
document.writeln("            }");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    ");
document.writeln("    <!-- 流量卡广告弹窗 -->");
document.writeln("    <div id=\"advertised-modal\" class=\"ad-modal\">");
document.writeln("        <div class=\"modal-content\">");
document.writeln("            <div class=\"ad-badge\">限时优惠</div>");
document.writeln("            <div class=\"modal-header\">");
document.writeln("                <h2><i class=\"fas fa-sim-card\"></i> ☎️ 大额流量卡免费申领</h2>");
document.writeln("                <p><i class=\"fas fa-car\"></i> 🚘 陌轩通讯 每日上新 🆕</p>");
document.writeln("                <span class=\"close-button\">&times;</span>");
document.writeln("            </div>");
document.writeln("            <div class=\"modal-body\">");
document.writeln("                <!-- 新增广告图片 -->");
document.writeln("                <div class=\"ad-image\">");
document.writeln("                    <img src=\"https://s2.loli.net/2025/06/04/XsehWozJNU6kZVA.jpg\" alt=\"流量卡广告\">");
document.writeln("                </div>");
document.writeln("                ");
document.writeln("                <div class=\"links-container\">");
document.writeln("                    <div class=\"link-item\">");
document.writeln("                        <div class=\"link-icon\">➜</div>");
document.writeln("                        <div class=\"link-text\">");
document.writeln("                            <a href=\"https://sourl.cn/yrm8S6\" target=\"_blank\">https://sourl.cn/yrm8S6</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"link-item\">");
document.writeln("                        <div class=\"link-icon\">➜</div>");
document.writeln("                        <div class=\"link-text\">");
document.writeln("                            <a href=\"https://sourl.cn/ADdLJZ\" target=\"_blank\">https://sourl.cn/ADdLJZ</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                ");
document.writeln("                <p><i class=\"fas fa-tag\" style=\"color: #27ae60;\"></i> 💰免费申领，邮费全免，非物联卡</p>");
document.writeln("                <p><i class=\"fas fa-check-circle\" style=\"color: #e74c3c;\"></i> 🔴缺流量卡可以冲，支持异地注销！</p>");
document.writeln("                <p><i class=\"fas fa-exclamation-triangle\" style=\"color: #9b59b6;\"></i> 🟣✋慢🈚️，若下架可购同类卡片</p>");
document.writeln("                <p><i class=\"fas fa-id-card\" style=\"color: #e74c3c;\"></i> 🔴全部官方卡，需真实信息办理</p>");
document.writeln("                ");
document.writeln("                <div class=\"tags\">");
document.writeln("                    <div class=\"tag\">#好卡推荐</div>");
document.writeln("                    <div class=\"tag\">#电话卡</div>");
document.writeln("                    <div class=\"tag\">#流量卡</div>");
document.writeln("                </div>");
document.writeln("                ");
document.writeln("                <div class=\"countdown-bar\">");
document.writeln("                    <div class=\"countdown-progress\"></div>");
document.writeln("                </div>");
document.writeln("                <div class=\"countdown-text\">10秒钟后自动关闭</div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <script>");
document.writeln("        document.addEventListener(\'DOMContentLoaded\', function() {");
document.writeln("            // 获取元素");
document.writeln("            var adModal = document.getElementById(\"advertised-modal\");");
document.writeln("            var closeButton = document.querySelector(\".close-button\");");
document.writeln("            var countdownProgress = document.querySelector(\".countdown-progress\");");
document.writeln("            var countdownText = document.querySelector(\".countdown-text\");");
document.writeln("            var countdownTimer;");
document.writeln("            var timeLeft = 10; // 倒计时时间（秒）");
document.writeln("            ");
document.writeln("            // 显示广告弹窗");
document.writeln("            function showAd() {");
document.writeln("                adModal.style.display = \"flex\";");
document.writeln("                startAutoClose();");
document.writeln("            }");
document.writeln("            ");
document.writeln("            // 开始10秒自动关闭");
document.writeln("            function startAutoClose() {");
document.writeln("                // 重置倒计时时间");
document.writeln("                timeLeft = 10;");
document.writeln("                updateCountdownText();");
document.writeln("                ");
document.writeln("                // 重置进度条动画");
document.writeln("                countdownProgress.style.animation = \'none\';");
document.writeln("                setTimeout(() => {");
document.writeln("                    countdownProgress.style.animation = \'countdown 10s linear forwards\';");
document.writeln("                }, 10);");
document.writeln("                ");
document.writeln("                // 清除之前的计时器");
document.writeln("                if (countdownTimer) clearInterval(countdownTimer);");
document.writeln("                ");
document.writeln("                // 每秒更新倒计时文本");
document.writeln("                countdownTimer = setInterval(function() {");
document.writeln("                    timeLeft--;");
document.writeln("                    updateCountdownText();");
document.writeln("                    ");
document.writeln("                    if (timeLeft <= 0) {");
document.writeln("                        closeAd();");
document.writeln("                    }");
document.writeln("                }, 1000);");
document.writeln("            }");
document.writeln("            ");
document.writeln("            // 更新倒计时文本");
document.writeln("            function updateCountdownText() {");
document.writeln("                countdownText.textContent = `${timeLeft}秒钟后自动关闭`;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            // 关闭广告弹窗");
document.writeln("            function closeAd() {");
document.writeln("                adModal.style.display = \"none\";");
document.writeln("                // 清除计时器");
document.writeln("                if (countdownTimer) clearInterval(countdownTimer);");
document.writeln("            }");
document.writeln("            ");
document.writeln("            // 点击关闭按钮时关闭弹窗");
document.writeln("            closeButton.addEventListener(\'click\', closeAd);");
document.writeln("            ");
document.writeln("            // 点击弹窗外的区域时关闭弹窗");
document.writeln("            adModal.addEventListener(\'click\', function(event) {");
document.writeln("                if (event.target === adModal) {");
document.writeln("                    closeAd();");
document.writeln("                }");
document.writeln("            });");
document.writeln("            ");
document.writeln("            // 页面加载时显示广告（每次刷新都显示）");
document.writeln("            setTimeout(showAd, 1500);");
document.writeln("        });");
document.writeln("    </script>");
document.writeln("");